<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-08T12:59:03Z" name="Default suite" finished-at="2023-08-08T12:59:20Z" duration-ms="17533">
    <groups>
    </groups>
    <test started-at="2023-08-08T12:59:03Z" name="Default test" finished-at="2023-08-08T12:59:20Z" duration-ms="17533">
      <class name="testclass.SampleTestclass">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:02Z" name="beforeSuite" finished-at="2023-08-08T18:29:03Z" duration-ms="1061" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="setData()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:03Z" name="setData" finished-at="2023-08-08T18:29:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:03Z" name="beforeClass" finished-at="2023-08-08T18:29:03Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:03Z" name="beforeMethod" finished-at="2023-08-08T18:29:10Z" duration-ms="7069" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="loginWithInvalidDetails()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:10Z" name="loginWithInvalidDetails" finished-at="2023-08-08T18:29:20Z" duration-ms="10425" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:60)
	at utils.Reporter.reportStep(Reporter.java:70)
	at utils.SeMethods.locateElement(SeMethods.java:103)
	at pages.LoginPage.closeicon(LoginPage.java:21)
	at testclass.SampleTestclass.loginWithInvalidDetails(SampleTestclass.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidDetails -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:20Z" name="afterMethod" finished-at="2023-08-08T18:29:20Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:20Z" name="afterTest" finished-at="2023-08-08T18:29:20Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testclass.SampleTestclass@35841320]" started-at="2023-08-08T18:29:20Z" name="afterSuite" finished-at="2023-08-08T18:29:21Z" duration-ms="933" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testclass.SampleTestclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
